<div class="tabbable tabs-left" align="left">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">About Me</a></li>
        <li><a href="#tab2" data-toggle="tab">About This Site</a></li>
        <li><a href="#tab3" data-toggle="tab">About CS50x</a></li>
        <li><a href="#tab4" data-toggle="tab">Visitors</a></li>
        <li><a href="#tab5" data-toggle="tab">Contact</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab1">
            <p class="well well-small">
                Hello world. My name is Shazvi Ahmed and I'm from Sri Lanka(that little island south of India, for those unfamiliar). I'm <?php echo(floor((time() - strtotime("1989-04-27"))/31556926));//current age?> years old and while I have a background in accounting, I'm a tech enthusiast at heart who is conflicted between web programming and system administration. I'm currently working as a web developer and plan on geting qualified in that field. That's about all there is to know about me, so let's move on.
            </p>
        </div>
        <div class="tab-pane" id="tab2">
            <p class="well well-small">
                I started this site as part of my final project for <a href="https://www.edx.org/courses/HarvardX/CS50x/2012/about">CS50x</a> and have been maintaining it as a hobby ever since. It's a website written in php that saves notes, memos, reminders in an SQL database which also demonstrates the use of <a href="https://mailgun.com">Mailgun</a> and cron jobs to send the reminders as an email on the due date. The main page displays the notes, which can be stored in multiple notebooks and sorted by any category thanks to Kryogenix's <a href="http://www.kryogenix.org/code/browser/sorttable/">sorttable</a> plugin. The aesthetics are powered by <a href="http://getbootstrap.com/2.3.2/index.html">Twitter Bootstrap</a> and <a href="http://jqueryui.com">Jquery ui</a> while the calendar view allows the user to see all the notes/entries for the month in an organized table. Furthermore, the site also has an instant search feature that allows you to search through all your notes while typing or by tags, with <a href="http://bartaz.github.io/sandbox.js/jquery.highlight.html">text highlighting</a>. <del>And finally, there's the ability to sync your reminders to Google Calendar which is implemented using the <a href="https://code.google.com/p/google-api-php-client/">Google api php client</a> library</del> <ins>Calendar sync has been turned off due to unfixed bugs in my code</ins>. That awesome title animation above is built on the work of Google and <a href="https://github.com/robhawkes/google-bouncing-balls">Rob Hawkes</a>, whereas, the standard title banners are generated by <a href="http://www.textfx.co/">Textfx</a> and <a href="http://neswork.com/logo-generator/twitter-font">Twitter Font</a>.
            </p>
            <p>
                The mobile version of this site can be accessed at <a href="http://mobi.memento.site90.net">mobi.memento.site90.net</a> although it's obviously not going to render correctly on a PC. Redirects to this site on a mobile device are triggered by the <a href="http://mobiledetect.net">Mobile Detect</a> library.
                Source for this site can be found <a href="https://github.com/shazvi/Memento">here</a>. Updated as of April 1st 2013.
            </p>
        </div>
        <div class="tab-pane" id="tab3">
            <p class="well well-small">
                <a href="https://www.edx.org/courses/HarvardX/CS50x/2012/about">CS50x</a> is an online course provided freely by Harvard at <a href="http://www.edx.org">Edx.org</a> as part of their open courseware initiative. The following are all the programming/scripting languages I've learned during my time with CS50x
            </p>
            <ul>
                <li>PHP</li>
                <li>MySQL</li>
                <li>HTML</li>
                <li>CSS</li>
                <li>Javascript/jQuery</li>
                <li>C Programming language</li>
                <li>Scratch</li>
            </ul>
            <p class="well well-small">
                While you're here, you should check out my first CS50x project written in Scratch called <a target="_blank" href="http://scratch.mit.edu/projects/3052886/">Draw Something Twist</a>.
            </p>
        </div>
        <div class="tab-pane" id="tab4">
            <p class="well well-small">
                If you're just here to check out the site, you're more than welcome to register for an account(which can be deleted at any time). If, however, you do not wish to do so, you can <a href="<?php echo base_url();?>page/demo">click here</a> to look around in the demo page, maybe even leave me a note :)
            </p>
        </div>
        <div class="tab-pane" id="tab5">
            <p class="well well-small">
                Email: <a href="mailto:shazvi@outlook.com" target="_blank">shazvi@outlook.com</a><br/>
                Facebook: <a href="http://www.facebook.com/shazvi.ahmed" target="_blank">Shazvi Ahmed</a><br/>
                Twitter: <a href="https://twitter.com/cybertox544" target="_blank">@Cybertox544</a>
            </p>
        </div>
    </div>
</div>